<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-HD87JMG" failures="1" tests="7" name="Surefire test" time="0.031" errors="0" timestamp="2025-08-22T21:33:33 EEST">
  <testcase classname="Test1" name="testAssertEquals" time="0.005"/>
  <testcase classname="Test1" name="testAssertFalse" time="0.0"/>
  <testcase classname="Test1" name="testAssertNotEquals" time="0.001"/>
  <testcase classname="Test1" name="testAssertNotNull" time="0.0"/>
  <testcase classname="Test1" name="testAssertNull" time="0.0"/>
  <testcase classname="Test1" name="testAssertTrue" time="0.001"/>
  <testcase classname="Test1" name="testForceFail" time="0.001">
    <failure type="java.lang.AssertionError" message="Condition was false - failing the test deliberately">
      <![CDATA[java.lang.AssertionError: Condition was false - failing the test deliberately
at Test1.testForceFail(Test1.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testForceFail -->
  <testcase classname="Test1" name="testSoftAssertExample" time="0.0">
    <ignored/>
  </testcase> <!-- testSoftAssertExample -->
</testsuite> <!-- Surefire test -->
